.github/labeler.yml
.github/workflows/pr-title-validation.yml

For PR titles we agreed to use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).
- pr-title-validation.yml Added
- labeler.yml Updated

chore(actions): Add pr-title validation & Update labeler

---

client/src/app/components/pull-request-table/pull-request-table.component.html
client/src/app/components/pull-request-table/pull-request-table.component.ts
client/src/app/pages/environment-list/environment-list.component.html

https://github.com/user-attachments/assets/88aa3412-317e-40ac-8015-8808fb957cb1

feat: Frontend improvements

---

client/src/app/components/branches-table/branches-table.component.html
client/src/app/components/branches-table/branches-table.component.spec.ts
client/src/app/components/branches-table/branches-table.component.ts
client/src/app/components/pull-request-table/pull-request-table.component.html
client/src/app/components/pull-request-table/pull-request-table.component.ts
client/src/app/core/modules/openapi/model/branch-info-dto.ts
client/src/app/pages/ci-cd/ci-cd.component.html
client/src/app/pages/ci-cd/ci-cd.component.ts
client/src/icons.module.ts
server/application-server/openapi.yaml
server/application-server/src/main/java/de/tum/cit/aet/helios/branch/BranchInfoDTO.java

Implemented Branches tab in client

chore(feat): Branches View Client

---

client/src/app/core/services/pipeline.ts

Add better pipeline groups for Artemis (hardcoded for now)

feat: Add better pipeline groups for Artemis (hardcoded for now)

---

client/src/app/core/modules/openapi/sdk.gen.ts
client/src/app/core/modules/openapi/types.gen.ts
client/src/app/pages/branch-details/branch-details.component.ts
server/application-server/openapi.yaml
server/application-server/src/main/java/de/tum/cit/aet/helios/branch/BranchController.java

fix: Branch Detail Not Loading

---

client/src/app/components/pull-request-table/pull-request-table.component.html
client/src/app/components/pull-request-table/pull-request-table.component.ts
client/src/app/core/modules/openapi/schemas.gen.ts
client/src/app/core/modules/openapi/types.gen.ts
server/application-server/openapi.yaml
server/application-server/src/main/java/de/tum/cit/aet/helios/github/sync/GitHubDataSyncService.java
server/application-server/src/main/java/de/tum/cit/aet/helios/gitrepo/GitRepository.java
server/application-server/src/main/java/de/tum/cit/aet/helios/issue/Issue.java
server/application-server/src/main/java/de/tum/cit/aet/helios/label/Label.java
server/application-server/src/main/java/de/tum/cit/aet/helios/label/LabelInfoDto.java
server/application-server/src/main/java/de/tum/cit/aet/helios/label/LabelRepository.java
server/application-server/src/main/java/de/tum/cit/aet/helios/label/github/GitHubLabelConverter.java
server/application-server/src/main/java/de/tum/cit/aet/helios/label/github/GitHubLabelMessageHandler.java
server/application-server/src/main/java/de/tum/cit/aet/helios/label/github/GitHubLabelSyncService.java
server/application-server/src/main/java/de/tum/cit/aet/helios/pullrequest/PullRequestBaseInfoDto.java
server/application-server/src/main/java/de/tum/cit/aet/helios/pullrequest/PullRequestInfoDto.java
server/application-server/src/main/java/de/tum/cit/aet/helios/pullrequest/github/GitHubPullRequestSyncService.java

- Label entity
- Syncing of Labels (of PRs) & Webhook listener
- Client changes
- word-breaking
-  color adjustments

feat: Get PR Labels and Show in Client

---

client/src/app/components/pipeline/pipeline.component.ts
client/src/app/core/modules/openapi/sdk.gen.ts
client/src/app/core/modules/openapi/types.gen.ts
server/application-server/openapi.yaml
server/application-server/src/main/java/de/tum/cit/aet/helios/workflow/WorkflowRunController.java

- GitHub Account without having any additional access-rights (e.g. admin, owner)
- ...
1. Log in to Helios as a Developer
2. Navigate to Settings
3. ...

fix: Fetch Workflow Runs error resolved

---

server/application-server/src/main/java/de/tum/cit/aet/helios/github/GitHubService.java

This error was caused because of user-permission was trying to send POST request. Changed it to GET. I minor change

fix: Permission error

---

server/application-server/src/main/java/de/tum/cit/aet/helios/github/GitHubService.java

- GitHub Account without having any additional access-rights (e.g. admin, owner)
- ...
1. Log in to Helios as a Developer
2. Navigate to Settings
3. ...

fix: Changed Request Builder for Github Service

---

client/src/environments/environment.prod.ts
nginx.conf
server/application-server/src/main/java/de/tum/cit/aet/helios/config/SecurityConfig.java
server/application-server/src/main/java/de/tum/cit/aet/helios/user/github/GitHubUserConverter.java

Domain name changed from helios.artemis.cit.tum.de to helios.aet.cit.tum.de

chore: Update domain to helios.aet.cit.tum.de

---

.github/ISSUE_TEMPLATE/1-bug-report.yml
.github/ISSUE_TEMPLATE/2-feature-request.yml

- GitHub Account without having any additional access-rights (e.g. admin, owner)
- ...
1. Log in to Helios as a Developer
2. Navigate to Settings
3. ...

feat: Create issue form

---

server/application-server/src/main/java/de/tum/cit/aet/helios/pullrequest/PullRequestRepository.java
server/application-server/src/main/java/de/tum/cit/aet/helios/pullrequest/PullRequestService.java

Refer to https://github.com/ls1intum/Helios/issues/226

fix: Get all the PRs in sorted by updatedAt

---

client/src/app/components/branches-table/branches-table.component.html
client/src/app/components/branches-table/branches-table.component.ts

feat: Separate protected branches

---

client/src/app/components/pull-request-table/pull-request-table.component.ts

Refer to https://github.com/ls1intum/Helios/issues/255

fix: Use purple for merged PR icon

---

.github/workflows/flyway-validate.yml
.github/workflows/prod.yml

chore: Validate flyway on push to main

---

.github/workflows/prod.yml

Fixes #287. Right now, there is a workflow that automatically validates the migration when deploying to production. However, the deployment workflow itself does not wait for the result of the validation. The PR changes that.

fix: Make deploy task wait for flyway validation

---

server/application-server/src/main/java/de/tum/cit/aet/helios/deployment/github/GitHubDeploymentSyncService.java

Missing `@Transactional` was causing and exception while processing deployment
- The error
- After the `@Transactional`
- The UI is also reflects

fix: LOB stream error when processing deployment

---

server/application-server/src/main/java/de/tum/cit/aet/helios/deployment/github/GitHubDeploymentSyncService.java

Deployments were being reset to `UNKNOWN` on subsequent syncs, overwriting the updated state set by the webhook handler.
This change adds a check to skip processing if a deployment already exists in the database, ensuring that the correct state is maintained after the initial sync.

fix: UNKNOWN deployment status after second sync

---

client/src/app/components/pull-request-table/pull-request-table.component.ts
client/src/app/pages/environment-deployment-history/environment-deployment-history.component.html

- Added Pagination for Activity History
- Filtering PR's was not working for users with username containing uppercase letters. Changed the comparison to lowercase comparison

fix: Filter PR Fix & Pagination for activity history

---

.github/renovate.json
.github/workflows/docs.yml
.github/workflows/enforce-staging-source-branch.yml
.github/workflows/flyway-validate.yml
.github/workflows/pr-title-validation.yml
.github/workflows/prod.yml
.github/workflows/test.yml
.github/workflows/validate-openapi.yml

Updates on default branch change, renaming `main` to `staging` excluding the deployment!

chore: Workflow updates after default branch change

---

.github/workflows/mock-staging-deployment-helios.yml

Dummy staging deployment workflow

chore: Add mock staging deployment workflow

---

server/application-server/src/main/java/de/tum/cit/aet/helios/deployment/DeploymentService.java
server/application-server/src/main/java/de/tum/cit/aet/helios/deployment/github/GitHubDeploymentSyncService.java
server/application-server/src/main/java/de/tum/cit/aet/helios/pullrequest/PullRequestRepository.java

Fixed error related to deployment if there are more than one PRs with same branch:

fix: PR deployment match error

---

.github/workflows/build_docker.yml
.github/workflows/staging.yml
client/Dockerfile
client/angular.json
client/src/environments/environment.staging.ts
server/application-server/src/main/resources/application-staging.yml

chore: Staging setup

---

client/src/app/core/services/permission.service.ts
server/application-server/src/main/java/de/tum/cit/aet/helios/config/GitHubJwtAuthenticationConverter.java

I am a test server admin but don't have admin permissions in the Artemis repository. Therefore, I need additional access rights. (See #344)
I added myself to the list of Helios admins who are not Artemis maintainers.

chore: Add additional test server admin

---

client/src/app/components/environments/environment-list/environment-list-view.component.html
client/src/app/components/environments/environment-list/environment-list-view.component.ts
server/application-server/src/main/java/de/tum/cit/aet/helios/deployment/DeploymentService.java
server/application-server/src/main/java/de/tum/cit/aet/helios/environment/EnvironmentService.java
server/application-server/src/main/java/de/tum/cit/aet/helios/workflow/github/GitHubWorkflowRunSyncService.java

- Lock button is not clickable when environment is enabled (check out in helios staging environment)
- Lock button is shown when environment is disabled (check out in helios staging environment)
- Unlock not possible after failure of deployment (see below)
https://github.com/user-attachments/assets/17c80950-ab40-41c9-81c3-16931537183b
```
2025-02-26T21:36:35.363+01:00  INFO 17454 --- [Helios] [         nats:4] d.t.c.a.helios.nats.NatsConsumerService  : Received message with subject: github.ege-test-org.ege-env-test.deployment_status
2025-02-26T21:36:35.366+01:00  INFO 17454 --- [Helios] [         nats:4] d.g.GitHubDeploymentStatusMessageHandler : Received deployment status event for repository: ege-test-org/ege-env-test, deployment: 2244774726, action: created …
```

fix: Locking/Unlocking problem

---

docs/development/production/ls1intum.rst

Update documentation for repository owners

chore: Update documentation

---

server/application-server/lombok.config
server/application-server/src/main/java/de/tum/cit/aet/helios/auth/AuthService.java
server/application-server/src/main/java/de/tum/cit/aet/helios/branch/BranchController.java
server/application-server/src/main/java/de/tum/cit/aet/helios/commit/CommitController.java
server/application-server/src/main/java/de/tum/cit/aet/helios/commit/CommitService.java
server/application-server/src/main/java/de/tum/cit/aet/helios/config/GitHubJwtAuthenticationConverter.java
server/application-server/src/main/java/de/tum/cit/aet/helios/config/SecurityConfig.java
server/application-server/src/main/java/de/tum/cit/aet/helios/deployment/DeploymentController.java
server/application-server/src/main/java/de/tum/cit/aet/helios/deployment/LatestDeploymentUnion.java
server/application-server/src/main/java/de/tum/cit/aet/helios/deployment/github/adapter/GhDeploymentSourceAdapter.java
server/application-server/src/main/java/de/tum/cit/aet/helios/deployment/github/adapter/GitHubDeploymentSourceAdapter.java
server/application-server/src/main/java/de/tum/cit/aet/helios/environment/EnvironmentController.java
server/application-server/src/main/java/de/tum/cit/aet/helios/github/GitHubDeploymentIterator.java
server/application-server/src/main/java/de/tum/cit/aet/helios/github/GitHubService.java
server/application-server/src/main/java/de/tum/cit/aet/helios/gitrepo/RepositoryController.java
server/application-server/src/main/java/de/tum/cit/aet/helios/gitrepo/RepositoryService.java
server/application-server/src/main/java/de/tum/cit/aet/helios/gitreposettings/GitRepoSettingsController.java
server/application-server/src/main/java/de/tum/cit/aet/helios/gitreposettings/GitRepoSettingsService.java
server/application-server/src/main/java/de/tum/cit/aet/helios/gitreposettings/WorkflowGroupMembershipService.java
server/application-server/src/main/java/de/tum/cit/aet/helios/gitreposettings/WorkflowGroupService.java
server/application-server/src/main/java/de/tum/cit/aet/helios/http/HttpClientConfig.java
server/application-server/src/main/java/de/tum/cit/aet/helios/http/HttpClientRateLimitInterceptor.java
server/application-server/src/main/java/de/tum/cit/aet/helios/nats/NatsConfig.java
server/application-server/src/main/java/de/tum/cit/aet/helios/nats/NatsErrorListener.java
server/application-server/src/main/java/de/tum/cit/aet/helios/permissions/UserPermissionsController.java
server/application-server/src/main/java/de/tum/cit/aet/helios/pullrequest/PullRequestController.java
server/application-server/src/main/java/de/tum/cit/aet/helios/workflow/WorkflowController.java
server/application-server/src/main/java/de/tum/cit/aet/helios/workflow/WorkflowRunController.java
server/application-server/src/main/java/de/tum/cit/aet/helios/workflow/WorkflowRunService.java
server/application-server/src/main/java/de/tum/cit/aet/helios/workflow/WorkflowService.java

Make use of the `@RequiredArgsConstructor` to reduce code lines and also error proneness

refactor: use required args constructor annotation

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
LICENSE
SECURITY.md

This PR adds standard community documentation files.
- Added `CODE_OF_CONDUCT.md` 
- Added `CONTRIBUTING.md`
- Updated `LICENSE` file with current information
- Added `SECURITY.md`

chore(docs): add community standards files

---

docs/development/local/setup.rst
server/application-server/src/main/java/de/tum/cit/aet/helios/workflow/GitHubWorkflowContext.java
server/application-server/src/main/java/de/tum/cit/aet/helios/workflow/WorkflowRun.java
server/application-server/src/main/java/de/tum/cit/aet/helios/workflow/WorkflowRunService.java
server/application-server/src/main/java/de/tum/cit/aet/helios/workflow/github/GitHubWorkflowRunMessageHandler.java
server/application-server/src/main/resources/application-dev.yml
server/application-server/src/main/resources/application-prod.yml
server/application-server/src/main/resources/application-staging.yml
server/application-server/src/main/resources/db/migration/V18__add_new_column_to_workflow_run.sql

Refer to https://github.com/ls1intum/Helios/issues/575

fix: WorkflowRun event listener for worflow_run event type

---

client/src/app/pages/environment-deployment-history/environment-deployment-history.component.html
client/src/app/pages/environment-deployment-history/environment-deployment-history.component.ts

mini-minor change again.
Added environment name into activity history page.

feat: Environment name added to activity history

---

server/application-server/src/main/java/de/tum/cit/aet/helios/branch/BranchService.java

See the issue or sentry for more infos

fix: check if date is null before comparing

---

client/src/app/components/footer/footer.component.html
client/src/app/components/footer/footer.component.ts
client/src/app/components/navigation-bar/navigation-bar.component.html
client/src/app/components/navigation-bar/navigation-bar.component.ts
client/src/app/components/profile-nav-section/profile-nav-section.component.html
client/src/app/components/profile-nav-section/profile-nav-section.component.ts
client/src/app/pages/main-layout/main-layout.component.html
client/src/app/pages/main-layout/main-layout.component.ts

refactor: apply header, sidebar and footer ui guidelines

---

server/application-server/src/main/java/de/tum/cit/aet/helios/environment/github/GitHubEnvironmentConverter.java

fixed a minor issue on data sync for getting protection rules

fix: update protection rules

---

server/application-server/src/main/java/de/tum/cit/aet/helios/branch/BranchInfoDto.java
server/application-server/src/main/java/de/tum/cit/aet/helios/branch/BranchService.java
server/application-server/src/main/java/de/tum/cit/aet/helios/commit/CommitRepository.java
server/application-server/src/main/java/de/tum/cit/aet/helios/gitrepo/GitRepoRepository.java
server/application-server/src/main/java/de/tum/cit/aet/helios/gitrepo/RepositoryService.java
server/application-server/src/main/java/de/tum/cit/aet/helios/releaseinfo/ReleaseInfoService.java
server/application-server/src/test/java/de/tum/cit/aet/helios/branch/BranchServiceTest.java

Refer to https://github.com/ls1intum/Helios/issues/227

fix: wrong branch information

---

server/application-server/src/main/java/de/tum/cit/aet/helios/tests/TestResultProcessor.java
server/application-server/src/main/java/de/tum/cit/aet/helios/tests/TestResultService.java
server/application-server/src/main/java/de/tum/cit/aet/helios/tests/TestSuiteRepository.java

- GitHub Account without having any additional access-rights (e.g. admin, owner)
- ...
1. Log in to Helios as a Developer
2. Navigate to Settings
3. ...

fix: Remove sorting by changed state in test results to improve performance and do not save logs for passed tests

---

client/src/app/components/release-candidate-deployment-table/release-candidate-deployment-table.component.ts
client/src/app/core/modules/openapi/schemas.gen.ts
client/src/app/core/modules/openapi/types.gen.ts
server/application-server/openapi.yaml
server/application-server/src/main/java/de/tum/cit/aet/helios/deployment/DeployRequest.java
server/application-server/src/main/java/de/tum/cit/aet/helios/github/GitHubService.java

Passing tag name as a branch for the workflow dispatch. This works without problems in GitHub but our testserver-deployment.yml workflow doesn't handle finding build with releases.

fix: release deployments

---

client/src/app/app.config.ts
client/src/app/core/modules/markdown/markdown.pipe.ts

There were some issues with the markdown pipe, where the bg color was not set correctly for dark mode

fix: markdown and tabs issue

---

client/src/app/components/branches-table/branches-table.component.html
client/src/app/components/branches-table/branches-table.component.ts

Record for
Filtering Branches List View by 'Last 7 days'
Expand/Collapse all branches
P.S This should be tested with Artemis data since we are recursively traversing all the nodes, we should observe what happens with a lot of data.
https://github.com/user-attachments/assets/ace4d7c0-417f-442f-84a6-6dac297ef831

feat: Branches List View Filter by last 7 days and Expand/Collapse All

---

server/application-server/src/main/java/de/tum/cit/aet/helios/github/GitHubService.java
server/application-server/src/main/java/de/tum/cit/aet/helios/releaseinfo/ReleaseInfoService.java

Note: bases on generating release notes pr
Can be tested on repositories where the keycloak idp is installed in repository. (on development we use Helios-githubApp-local for authentication, so it can be tested only with ege-test-org repositories)

feat: publish release with user token

---

client/src/app/components/pipeline/test-results/pipeline-test-results.component.ts
client/src/app/components/pull-request-table/pull-request-table.component.html

- Removed duplicated icons
- Fixed truncate in pr title

fix: wrong icons & pr title truncate problem

---

client/src/app/pages/user-settings/user-settings.component.html

fix: dark mode issue in user settings page

---

client/src/app/components/environments/environment-accordion/environment-accordion.component.html
client/src/app/components/environments/environment-accordion/environment-accordion.component.ts

Screencast
https://github.com/user-attachments/assets/f13fbf80-b5f2-4550-823b-d9fa673468be

feat: Added Link to GitHub workflow run for deployments

---

client/src/app/components/environments/environment-accordion/environment-accordion.component.html
client/src/app/components/environments/environment-accordion/environment-accordion.component.ts

feat: delete environment type tag

---

client/src/app/components/environments/environment-accordion/environment-accordion.component.html
client/src/app/components/environments/environment-accordion/environment-accordion.component.ts
client/src/app/components/environments/environment-actions/environment-actions.component.html
client/src/app/components/environments/environment-list/environment-list-view.component.html
client/src/app/components/environments/environment-list/environment-list-view.component.ts

- Moved installed apps from expanded environment view to collapsed environment view
- Updated CSS to show deploy button on mobile view.
- Changed search bar to search for installed apps, environment names, and environment display names
- Added filter option for environments to filter by availability and environment type.
- Added highlighting environment locked by the current user
https://github.com/user-attachments/assets/91a13f73-13bd-40a2-8cc7-138134a1e39b

feat: Environment List View Enhancements

---

client/src/app/components/environments/deployment-state-tag/deployment-state-tag.component.html
client/src/app/components/release-candidate-deployment-table/release-candidate-deployment-table.component.html
client/src/app/components/release-candidate-table/release-candidate-table.component.html
client/src/app/pages/release-candidate-details/release-candidate-details.component.html

fix: release candidate deploy table
