ls1intum/Helios

client/src/app/components/pipeline/pipeline.component.html
client/src/app/components/pipeline/pipeline.component.ts
client/src/icons.module.ts

Refer to https://github.com/ls1intum/Helios/issues/163
- Fixed the issue where an extra dash was rendered unnecessarily.
- Added a message for pipeline groups with no workflow runs: "No workflow runs found."
`Having extra dash`
`If no workflowrun found, we don't show anything`
`Having extra dash - -> Fixed`
`If no workflowrun found, we don't show anything --> Informative text added`

fix: Workflow Grouping

---

client/src/app/pages/main-layout/main-layout.component.html
client/src/icons.module.ts

* Removed the settings icon from the main layout component, because it's currently unused (`client/src/app/pages/main-layout/main-layout.component.html`)
* Added new icons `IconExclamationMark` and `IconTimeDurationOff` to the import statement and the `icons` object in the icons module, because they are used by the deployment states, but not imported correctly. (`client/src/icons.module.ts`) [[1]](diffhunk://#diff-d087b05c840f170fdaa86fa16f6bc6e7a4fa2ea08fb0fee0d94f2e313db7f623R49-R50) [[2]](diffhunk://#diff-d087b05c840f170fdaa86fa16f6bc6e7a4fa2ea08fb0fee0d94f2e313db7f623R99-R100)

fix: Add missing deployment icons and remove settings icon from sidebar

---

client/src/app/app.component.ts

In #182 I added logic that would periodically refresh the access token. However, the query client middleware that sets the API token within the Authorization header of an API request retrieved the token only once after the page load.
This code updates the middleware to always get the latest token before a request. That fixes #149

fix: Get the latest token every request

---

server/application-server/src/main/java/de/tum/cit/aet/helios/environment/EnvironmentService.java

Fixed a bug where updating the environment with active set to true was unintentionally clearing the lock status. The intended behavior is to clear the previous lock information in the environment entity only when the environment is being re-enabled (i.e., transitioning from disabled to enabled). This ensures that no outdated lock data is retained.

fix: Lock issue on environment update

---

helios-example-realm.json

- Before this PR, we were using preffered_username or keycloak id for authentication purposes
- We were not able to match the logged in user with github User object.
- Added github_id into JWT, hence we can use the Github User object in necessary places.
- Already updated the realm in production and we are getting github_id in JWT payload. 
- This update is for managing local development
-  You need to delete your volume to start keycloak from scratch with updated helios-example-realm.json

feat: Added github id into keycloak JWT

---

client/src/app/components/pipeline/pipeline.component.html

This change addresses an issue where workflow groups and names were not displayed properly in the PR and Branch views, as reported in #258. Panels failed to wrap when space was limited, and workflow names were truncated.
- Added `flex-wrap` to ensure workflow panels wrap to the next row when they exceed available space.
- Introduced `max-w-[250px]` to limit panel widths.
- Replaced fixed width (`w-36`) for workflow names with flexible width (`w-full`) for full utilization of available space.
- Removed truncation (`truncate`) for names.

fix: Ensure workflow groups and names fit properly in PR and Branch views

---

client/src/app/components/branches-table/branches-table.component.html
client/src/app/components/branches-table/branches-table.component.ts
client/src/app/pipes/highlight.pipe.spec.ts
client/src/app/pipes/highlight.pipe.ts

The change enhances user experience by automatically expanding nodes in the tree view during branch search and highlighting the matching text.
- Implemented automatic expansion of tree nodes when a branch search matches any part of the tree.
- Added `HighlightPipe` to handle text highlighting for matched search terms efficiently.
- Included tests for the `HighlightPipe`.
- Added text highlighting for matched search terms to improve visual clarity.
https://github.com/user-attachments/assets/84f7d7d2-2d6f-4c02-b545-a43579420d5c
**Question:** Should we consider highlighting only the leaf nodes instead of intermediate nodes? For example, if the search key is `feature`, we would not highlight `feature` itself but only `feature/add-new-tab` or similar leaf nodes in the tree.

fix: Expand nodes and highlight text on branch search

---

.github/workflows/flyway-validate.yml
server/application-server/src/main/resources/db/migration/V1__initial_schema.sql

Right now, Flyway validate PRs are failing for workflows that don't change anything about migrations. That will be addressed here.
The issue was that when checking any file changes within the migration directory `git diff` will return an error exit code if there are no changes. The PR updates that logic.

fix: Flyway validation not working properly for PRs

---

client/src/app/components/user-lock-info/user-lock-info.component.html
client/src/app/components/user-lock-info/user-lock-info.component.ts
client/src/app/pages/main-layout/main-layout.component.html
client/src/app/pages/main-layout/main-layout.component.ts
server/application-server/src/main/java/de/tum/cit/aet/helios/environment/Environment.java
server/application-server/src/main/java/de/tum/cit/aet/helios/environment/EnvironmentLockHistoryDto.java
server/application-server/src/main/java/de/tum/cit/aet/helios/environment/EnvironmentService.java

After locking an environment, the user currently sees their longest locked time on the sidebar. However, it's not completely clear what that time means. Additionally, it's not possible to navigate to the environments by clicking on the time even though users might want/expect that. That's why #168 was created.
- Move lock info of the user from the main layout component into its own
- Turn the info container into a link to the environment list, so users can unlock directly
- Add a tooltip that shows the environment that is locked and the latest deployment branch of that environment
- Add getLatestDeployment() function in environment for convenience and to avoid logic duplication
- Slight design change to show lock icon and time vertically because the sidebar got a lot wider when the timer …

feat: Show more details of a locked environment in tooltip

---

server/application-server/src/main/java/de/tum/cit/aet/helios/pullrequest/github/GitHubPullRequestSyncService.java

We were accidently setting the PRs as closed, removed the setting closed logic in pullrequest sync service.

fix: Remove setting PR Status to closed

---

client/src/app/pages/main-layout/main-layout.component.html
client/src/app/pages/main-layout/main-layout.component.ts

If the user is not logged in,  the readonly banner is shown to ensure the user is aware of it

feat: Add information banner if logged out

---

.github/workflows/flyway-validate.yml

We are only validating our Flyway migrations on the `main`-branch, this PR adds the check for the staging branch.

chore: Validate flyway on staging

---

server/application-server/src/main/java/de/tum/cit/aet/helios/commit/github/GitHubCommitConverter.java
server/application-server/src/main/resources/db/migration/V6__reduce_commit_length.sql

Currently we have a limit of 1023 characters for commit messages in the database, while the recommendation from github is somewhere around 70.
However there was currently a commit submitted to Artemis with a total length of over 2400 characters. 
This PR will truncate the commit messages longer than 255 and also applying it for already existing ones in the db

fix: Truncating commit messages when longer than 255 chars

---

server/application-server/src/main/java/de/tum/cit/aet/helios/releasecandidate/ReleaseCandidate.java

Currently all release candidates from every repository are returned for a request within a repository. With this PR this is limited to only return the release candidates of the certain repository.

fix: Add repository filter to release candidate

---

server/application-server/src/main/resources/db/migration/V10__add_on_delete_cascade.sql

`DB: there is already a transaction in progress (SQL State: 25001 - Error Code: 0)`
Use `./gradlew flywayClean flywayMigrate` after a new migration is created

fix: Transaction warning because of a migration script

---

client/src/app/components/environments/environment-list/environment-list-view.component.html
client/src/app/components/environments/environment-list/environment-list-view.component.ts
client/src/app/core/modules/openapi/@tanstack/angular-query-experimental.gen.ts
client/src/app/core/modules/openapi/sdk.gen.ts
client/src/app/core/modules/openapi/types.gen.ts
client/src/app/pages/main-layout/main-layout.component.html
client/src/app/pages/main-layout/main-layout.component.ts
client/src/app/pages/project-settings/project-settings.component.html
client/src/app/pages/project-settings/project-settings.component.ts
client/src/app/pages/release-candidate-details/release-candidate-details.component.html
client/src/app/pages/release-candidate-details/release-candidate-details.component.ts
client/src/icons.module.ts
server/application-server/openapi.yaml
server/application-server/src/main/java/de/tum/cit/aet/helios/releasecandidate/ReleaseCandidate.java
server/application-server/src/main/java/de/tum/cit/aet/helios/releasecandidate/ReleaseCandidateController.java
server/application-server/src/main/java/de/tum/cit/aet/helios/releasecandidate/ReleaseCandidateRepository.java
server/application-server/src/main/java/de/tum/cit/aet/helios/releasecandidate/ReleaseCandidateService.java

This PR adds the possibility to delete release candidates.

feat: Add delete of release candidates

---

client/src/main.ts

:mirror_ball: Open for discussion: This sentry integration helps reproducing the errors and debugging it with replaying the users behaviour in the moment the bug appears. IMO this improves our capabilities and helps us fix bugs in production faster and easier. What do you think @egekocabas @StefanNemeth @TurkerKoc @gbanu? 
Find more infos here: https://sentry.io/product/session-replay/

chore: Add replay integration for sentry

---

server/webhook-listener/requirements.txt

newest version of pydantic depends on older version of pydantic-core: 
```
ERROR: Cannot install -r /code/requirements.txt (line 22) and pydantic-core==2.29.0 because these package versions have conflicting dependencies.
The conflict is caused by:
The user requested pydantic-core==2.29.0
pydantic 2.10.6 depends on pydantic-core==2.27.2
To fix this you could try to:
loosen the range of package versions you've specified
remove package versions to allow pip to attempt to solve the dependency conflict
[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: pip install --upgrade pip
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

fix: Webhook-listener dependency update

---

client/src/app/components/environments/deployment-stepper/deployment-stepper.component.ts

Transition between pre-deployment and deployment was not properly handled. Fixed the issue with our new Deployment Type

fix: Deployment progress bar step transitions

---

docs/development/production/ls1intum.rst
server/application-server/src/main/java/de/tum/cit/aet/helios/deployment/DeploymentService.java

The current workflow dispatch configuration differentiates inputs based on environment types, which adds unnecessary complexity to the deployment process. Standardizing the inputs across all environments will simplify the deployment workflow and make it more maintainable.
refactor!: standardize workflow dispatch inputs for all environments
This change removes environment-specific input differentiation in the deployment workflow. Now all environments use the same standardized set of inputs:
- `branch_name`
- `commit_sha`
- `environment_name`
- `triggered_by`
BREAKING CHANGE: Environment-specific inputs have been removed. All deployments now use the same standardized input structure.
Key changes:
- Removed environment type checking logic
- Standardized workflow dispatch inputs across all …

feat: Dispatch workflows with unified inputs

---

client/src/app/components/pipeline/test-results/pipeline-test-results.component.html
client/src/app/components/pipeline/test-results/pipeline-test-results.component.ts

Right now, developers cannot filter specific test cases. Implements #407.
This PR enhances the test results view by introducing two new features:
- **Filter for Failed Tests:** Users can now toggle a filter to display only failed tests, making it easier to focus on issues.
- **Search Input for Failed Tests:** A search bar has been added to allow users to quickly find specific failed tests by name of the class or method
It also fixes the styling of the results in case the class name of a suite is too long.
Within the test results, set the filter to only include failed tests and/or filter by a suite/class name using the search input.
I'd still like to unify the logic with the table search component before this is not a draft PR anymore.

feat: Add filter for failed tests + search

---

.codacy.yaml
.github/workflows/test.yml
client/vite.config.mts

The exclude paths from codacy do not work correctly. Hopefully this will work. I removed the ** prefix, because that is not documented in codacy to work.

chore: Fix codacy exclude paths

---

.github/workflows/build_docker.yml
.github/workflows/docs.yml

Ensures that assets managed by Git LFS are properly included in both documentation and application builds by enabling LFS support in checkout actions.
Fixes #532

fix: include Git LFS assets in builds

---

compose.prod.yaml
compose.yaml

In order to be able to configure the keycloak for user impersonation we have to start the container with the flag `--features="token-exchange,admin-fine-grained-authz"`

chore: enable feature preview for keycloak

---

client/src/app/components/environments/environment-list/environment-list-view.component.html
client/src/app/components/environments/environment-list/environment-list-view.component.ts
client/src/app/core/modules/openapi/schemas.gen.ts
client/src/app/core/modules/openapi/types.gen.ts
client/src/app/pages/ci-cd/ci-cd.component.ts
server/application-server/openapi.yaml
server/application-server/src/main/java/de/tum/cit/aet/helios/deployment/LatestDeploymentUnion.java
server/application-server/src/main/java/de/tum/cit/aet/helios/environment/EnvironmentDto.java

I didn't want to overload the environment list component even more that's why added a link to the existing latest deployment tag.
https://github.com/user-attachments/assets/eeac0b13-fa36-4bda-a916-d17f2edcd72f
fixes https://github.com/ls1intum/Helios/issues/317

feat: link pr in the env view

---

client/src/app/components/environments/environment-list/environment-list-view.component.html
client/src/app/components/pipeline/pipeline.component.html

The pipeline currently can look a bit crowded when the job names are long. Additionally, the deployment actions in the environment list is wrapped weirdly when there is a lot of info.
- Truncate the names to only a single line and show the full name on hover in the pipeline
- Group the deployment actions in a single div so it stays together and disable wrap for big screens
Open a pipeline with a long enough job name and check the environment list with small and large screen sizes.
**Pipeline:**
**Environment list:**
Before:
After:

feat: Truncate pipeline names + fix wrap in environment list

---

client/src/app/components/pull-request-table/pull-request-table.component.html

Mini-minor change:
Added vertical padding into PR Table.
It's changed from this:
To this:

fix: PR Table View

---

client/src/app/components/deployment-selection/deployment-selection.component.html
client/src/app/components/environments/deployment-state-tag/deployment-state-tag.component.ts
client/src/app/components/environments/deployment-stepper/deployment-stepper.component.html
client/src/app/components/environments/deployment-stepper/deployment-stepper.component.ts
client/src/app/components/environments/environment-accordion/environment-accordion.component.html
client/src/app/components/environments/environment-accordion/environment-accordion.component.ts
client/src/app/components/environments/environment-actions/environment-actions.component.html
client/src/app/components/environments/environment-actions/environment-actions.component.ts
client/src/app/components/environments/environment-details/environment-details.component.html
client/src/app/components/environments/environment-details/environment-details.component.ts
client/src/app/components/environments/environment-list/environment-list-view.component.html
client/src/app/components/environments/environment-list/environment-list-view.component.ts
client/src/app/components/release-candidate-deployment-table/release-candidate-deployment-table.component.html
client/src/app/components/release-candidate-deployment-table/release-candidate-deployment-table.component.ts
client/src/icons.module.ts
server/application-server/src/main/java/de/tum/cit/aet/helios/deployment/DeploymentService.java
server/application-server/src/test/java/de/tum/cit/aet/helios/deployment/DeploymentServiceTest.java

Stephan wanted that students can also see staging environment in the pr/branch details view, but it is ok, that he still needs to approve it. (he said)
- Grouped environments by type
- Users with WRITE permissions can trigger staging deployment
- Added ugly approve button to navigate to GitHub, will be removed with auto approvals
- No locking for staging environments
- I didn't touch on deployment progress bar logic because it will change again once we have auto approvals
- In the current implementation, student can start deployment to staging environment, and Stephan and open Helios go to the environment list view and follow the link for the approval
- Split environment-list-view in several components that can be refactored individually
1. Student starts deployment in PR/branch view
2. …

feat: show all environments everywhere

---

server/application-server/src/main/java/de/tum/cit/aet/helios/releaseinfo/ReleaseInfoService.java
server/application-server/src/main/java/de/tum/cit/aet/helios/releaseinfo/releasecandidate/ReleaseCandidateRepository.java

release candidates were sorted by name in asc order which were showing the latest release last. Changed it to sort by createdAt date in desc order

fix: Release candidates sorting order

---

client/src/app/components/pipeline/test-results/pipeline-test-results.component.html
client/src/app/components/pipeline/test-results/pipeline-test-results.component.ts
client/src/app/core/modules/openapi/schemas.gen.ts
client/src/app/core/modules/openapi/types.gen.ts
server/application-server/openapi.yaml
server/application-server/src/main/java/de/tum/cit/aet/helios/tests/TestCase.java
server/application-server/src/main/java/de/tum/cit/aet/helios/tests/TestCaseStatistics.java
server/application-server/src/main/java/de/tum/cit/aet/helios/tests/TestCaseStatisticsRepository.java
server/application-server/src/main/java/de/tum/cit/aet/helios/tests/TestCaseStatisticsService.java
server/application-server/src/main/java/de/tum/cit/aet/helios/tests/TestResultProcessor.java
server/application-server/src/main/java/de/tum/cit/aet/helios/tests/TestResultService.java
server/application-server/src/main/java/de/tum/cit/aet/helios/tests/TestResultsDto.java
server/application-server/src/main/resources/db/migration/V27__remove_flakiness_fields_from_test_case_statistics.sql

**Failure Rate Updates:**
**Failure Rates and Flakiness Score:**
**Flakiness score calculation info pop-up:**
Removed isFlaky and FailureRate fields from TestcaseStatistics Entity.
Now we are only storing total runs and failed runs for default branch and all branches combined.
Then we are using this information to calculate failure rates and flakiness score.

feat: Failure rates for all branches 

---

client/src/app/components/pipeline/test-results/pipeline-test-results.component.html
client/src/app/components/pipeline/test-results/pipeline-test-results.component.ts

- Implemented a filter with slider component to filter logs by level including the higher severity logs.
Log levels: OFF, FATAL, ERROR, WARN, INFO, DEBUG, TRACE, ALL
if you choose ERROR then FATAL and OFF will be included
if you choose DEBUG then INFO, WARN, ERROR, FATAL, OFF will be included
- I also added log level coloring to the lines
- Lines that doesn't contain any log level is kept in the text all the time
- Matching logic: It looks for lines that contains following pattern -> | <uppercase_log_level> |
Screen recording:
https://github.com/user-attachments/assets/4dcdb979-cbeb-4ebc-af97-f26de8cdfa1f

feat: Filter logs by log level

---

server/application-server/src/main/java/de/tum/cit/aet/helios/config/AsyncConfig.java
server/application-server/src/main/java/de/tum/cit/aet/helios/workflow/github/GitHubWorkflowRunMessageHandler.java
server/application-server/src/main/java/de/tum/cit/aet/helios/workflow/github/GitHubWorkflowRunSyncService.java

We need to delay processing of GitHub `workflow_run` events by **10** (can be less or more) **seconds** so that the workflow has time to upload the `workflow-context` artifact. This artifact contains the `branch/SHA` information that triggered the workflow. Without waiting, we lose the ability to associate the run with the correct triggering branch/commit. We also need to ensure these events are processed sequentially, as our webhook processing is already sequential. 
- Added a single‐threaded TaskScheduler bean (workflowRunTaskScheduler) with poolSize(1) to guarantee tasks are handled one at a time.
- Refactored the workflow‐run handling to:
- Schedule `workflow_run` events to run 10 seconds later
- In `handleWorkflowRunEvent(...)`, we download the `workflow-context` artifact (if …

fix: add delayed processing for GitHub `workflow_run` events

---

.github/workflows/docs.yml
docs/conf.py
docs/development/local/keycloak_token_exchange.rst
docs/index.rst
docs/user_guide/deployments/testserver.rst

- Use relative path since the direct usage uses the organization path as an example `https://ls1intum.github.io/_static/images/user_guide/select-repo.png`

fix: docs image paths

---

client/src/app/components/dialogs/deploy-confirmation/deploy-confirmation.component.html
client/src/app/components/dialogs/deploy-confirmation/deploy-confirmation.component.ts
client/src/app/components/dialogs/lock-confirmation/lock-confirmation.component.html
client/src/app/components/dialogs/lock-confirmation/lock-confirmation.component.ts
client/src/app/components/dialogs/publish-draft-release-confirmation/publish-draft-release-confirmation.component.html
client/src/app/components/dialogs/publish-draft-release-confirmation/publish-draft-release-confirmation.component.ts
client/src/app/components/dialogs/secret-generate-confirmation/secret-generate-confirmation.component.html
client/src/app/components/dialogs/secret-generate-confirmation/secret-generate-confirmation.component.ts
client/src/app/components/environments/environment-list/environment-list-view.component.html
client/src/app/components/environments/environment-list/environment-list-view.component.ts
client/src/app/components/navigation-bar/navigation-bar.component.ts
client/src/app/components/release-candidate-deployment-table/release-candidate-deployment-table.component.html
client/src/app/components/release-candidate-deployment-table/release-candidate-deployment-table.component.ts
client/src/app/pages/project-settings/project-settings.component.html
client/src/app/pages/project-settings/project-settings.component.ts
client/src/app/pages/release-candidate-details/release-candidate-details.component.html
client/src/app/pages/release-candidate-details/release-candidate-details.component.ts
client/src/app/pages/repository-overview/connection-steps.ts

feat: improve confirmation dialogs

---

client/src/app/components/deployment-selection/deployment-selection.component.html
client/src/app/components/deployment-selection/deployment-selection.component.ts
client/src/app/components/environments/environment-accordion/environment-accordion.component.html
client/src/app/components/environments/environment-actions/environment-actions.component.html
client/src/app/components/environments/environment-list/environment-list-view.component.html
client/src/app/components/pipeline/pipeline.component.html
client/src/app/components/pipeline/pipeline.component.ts
client/src/app/components/pipeline/test-results/pipeline-test-results.component.html
client/src/app/components/pipeline/test-results/pipeline-test-results.component.ts
client/src/app/pages/pull-request-details/pull-request-details.component.html
client/src/app/pages/pull-request-details/pull-request-details.component.ts

https://github.com/user-attachments/assets/a163820c-4ebf-41e1-b846-434d9ed24bf4

refactor: pr/branch details & environment views

---

server/application-server/build.gradle
server/application-server/src/main/resources/application-prod.yml
server/application-server/src/main/resources/application-staging.yml

Since we added the `helios-status-spring-starter` library, it included its own `logback-spring.xml` that set all `de.tum.cit.aet.helios` Loggers to `ERROR`. Because our code uses the same package path, we weren’t seeing any `DEBUG` output (Connect to staging and check out the logs). By specifying:
```yaml
logging:
level:
de.tum.cit.aet.helios: DEBUG
```
in `application.yml`, we ensure our Helios classes log at `DEBUG`.

chore: configure `de.tum.cit.aet.helios` logging to `DEBUG`

---

README.md
server/helios-status-spring-starter/CHANGELOG.md
server/helios-status-spring-starter/PACKAGE_README.md
server/helios-status-spring-starter/README.md
server/helios-status-spring-starter/pom.xml
server/helios-status-spring-starter/src/main/java/de/tum/cit/aet/helios/HeliosClient.java
server/helios-status-spring-starter/src/main/java/de/tum/cit/aet/helios/autoconfig/HeliosStatusAutoConfiguration.java
server/helios-status-spring-starter/src/main/resources/logback-spring.xml

This PR removes the okhttp dependency in helios spring boot starter library. See the new `CHANGELOG.md` file

feat(library): remove okhttp dependency and use spring boot's `RestClient`
